### ISSUE TITLE
Missing fields in Company schema

### ISSUE THREAD

**Issue by PyAgni** [peopledatalabs/peopledatalabs-go#40]
The `employee_growth_rate_12_month_by_role` and `employee_growth_rate_12_month_by_role_v2` fields in the company record API response are not available in the Company model schema in this package. 

The example Company record provided [here](https://docs.peopledatalabs.com/docs/example-company-record) also has these. 

Can we have support for these fields in this package?

**Comment by vvillait88** [comment]
@PyAgni https://github.com/peopledatalabs/peopledatalabs-go/pull/41 will have `employee_growth_rate_12_month_by_role` added.  employee_growth_rate_12_month_by_role_v2 was mistakenly publicly published, when we release v28.0 you will have the option pass in updated_title_roles to the Company APIs and that will return v2 values in place of the current ones.

**Comment by PyAgni** [comment]
@vvillait88 Having `employee_growth_rate_12_month_by_role` is sufficient for our use case. Thanks!
