### ISSUE TITLE
"headline" field is missing from Schema Person

### ISSUE THREAD

**Issue by c-malecki** [peopledatalabs/peopledatalabs-go#43]
**Describe the bug**
The field "headline" is missing from the Person struct which prevents an API user from having access to the field

**To Reproduce**
Use the Person Enrichment API through Go library or check the Go documentation or schemas.go file to see the field is missing
https://github.com/peopledatalabs/peopledatalabs-go/blob/main/model/schemas.go
https://pkg.go.dev/github.com/peopledatalabs/peopledatalabs-go/v3@v3.2.0/model#Person

**Expected behavior**
The peopledatalabs client will unmarshal API responses into the Person struct with the inclusion of "headline"

**Screenshots**
N/A

**Additional context**
N/A

**Comment by vvillait88** [comment]
@c-malecki We've updated the Person Schema to include headline now
